openfoodfacts/openfoodfacts-query

src/domain/services/import.service.spec.ts
src/domain/services/import.service.ts
src/domain/services/query.service.spec.ts

bug: Wrap delete and insert of tags in a transaction

---

.github/workflows/container-deploy.yml

Use stunnel-client container for more security.
**NOTE:** already done in production

chore: change prod mongodb address (again)

---

.github/workflows/container-deploy.yml

Transposed staging and production

---

.env
.github/workflows/container-deploy.yml
Makefile
docker-compose.yml

Make work_mem and shared_buffers configurable and set values for staging and production
- #48

feat: Allow shared_buffers and work_mem to be set

---

src/domain/services/import.service.ts

fix: Analyze temp table once populated

---

src/domain/services/import.service.spec.ts
src/domain/services/import.service.ts

fix: Prevent errors when there are duplicate product codes

---

.github/labeler.yml
.github/workflows/label.yml

ci: Create label.yml

---

.github/workflows/auto-assign-pr.yml

- ci: Create auto-assign-pr.yml

ci: Create auto-assign-pr.yml

---

.github/workflows/release-please.yml

- ci: Create release-please.yml

ci: Create release-please.yml

---

.github/workflows/container-deploy.yml

Update container-deploy.yml to deploy automatically production to docker-prod-2 on Moji server.

chore: update deploy conf to deploy on docker-prod-2

---

.github/CODEOWNERS
.github/dependabot.yml

chore: Update dependabot.yml and CODEOWNERS

---

.github/dependabot.yml

fix: Fix PR naming

---

.github/workflows/container-build.yml

fix: Update action versions

---

.github/workflows/release-please.yml

fix: Fix release please

---

.github/workflows/container-build.yml

fix: Get 403 errors when pushing from dependabot

---

.github/workflows/container-build.yml

fix: Try setting permissions instead

---

src/domain/entities/product.ts
src/domain/services/import.service.spec.ts
src/domain/services/import.service.ts
src/domain/services/query.service.spec.ts
src/domain/services/settings.service.ts
src/migrations/.snapshot-query.json
src/migrations/Migration20241029165410.ts
test/global-setup.ts
tsconfig.json

- Fix PR#104 to use function compatible with PostgreSQL 12
- #103

fix: Re-implement changes from PR #104

---

.github/workflows/container-deploy.yml

fix: Fix PostgreSQL deploy script

---

Dockerfile

- Fix issue where countries.json is not copied to assets in the Dockerfile
- #11334

fix: Ensure countries.json is included in assets

---

src/domain/services/query.service.ts

- Was treating world queries as if they had multiple countries specified
- #11334

fix: Don't reject world queries

---

src/domain/services/import.service.spec.ts
src/domain/services/import.service.ts
src/domain/services/query.service.ts

- Fix detection of need for full reload to ignore extra tags
- #120

fix: A full reload is triggered every night once scans have been loaded

---

query/config.py
query/conftest.py
query/migrations/Migration20250614092300.py
query/models/query.py
query/services/query.py
query/services/query_count_test.py
query/services/query_find_test.py
query/services/scan_test.py
query/tables/product.py

- These operators are used on the Advanced Search Ingredients section
- #158
- https://github.com/openfoodfacts/openfoodfacts-server/issues/11755

feat: Support $lt, $gt, $gte and $lte queries

---

.github/workflows/container-build.yml
.github/workflows/container-deploy.yml
query/mongodb.py

- Seeing lots of timeout exceptions in off-query when connecting to MongoDB. Double the timeout from 1 to 2 seconds to see if this helps

fix: Double MongoDB timeout

---

query/models/query.py

- Negative offset or skip causes PostgreSQL errors

fix: Validate against negative limit / skip

---

.github/dependabot.yml

- Still getting a warning that the production group isn't being picked up

fix: Try adding an allow rule for production group to be picked up

---

.github/workflows/release-please.yml

chore: Set release please project type and token
